HTTP_STATUS = {
    "OK": 200,
    "CREATED": 201,
    "BAD_REQUEST": 400,
    "UNAUTHORIZED": 401,
    "FORBIDDEN": 403,
    "NOT_FOUND": 404,
    "CONFLICT": 409,
    "UNPROCESSABLE_ENTITY": 422,
    "INTERNAL_SERVER_ERROR": 500,
    "SERVICE_UNAVAILABLE": 503,
}

ERROR_CODES = {
    "VALIDATION_ERROR": "VALIDATION_ERROR",
    "INVALID_URL": "INVALID_URL",
    "MISSING_REQUIRED_FIELD": "MISSING_REQUIRED_FIELD",
    "AGENTQL_ERROR": "AGENTQL_ERROR",
    "PARSING_ERROR": "PARSING_ERROR",
    "SERVER_ERROR": "SERVER_ERROR",
    "SERVICE_UNAVAILABLE": "SERVICE_UNAVAILABLE",
    "PROXY_ERROR": "PROXY_ERROR",
    "BROWSER_ERROR": "BROWSER_ERROR",
}
